/*
 * Tavi020 Program Version
 *
 * This file is automatically generated from makefile
 */

#ifndef __TAVI020_VERSION_H
#define __TAVI020_VERSION_H

#define TAVI020_MAJORVERSION		2
#define TAVI020_MINORVERSION		1
#define TAVI020_PATCHLEVEL1		0
#define TAVI020_PATCHLEVEL2		15

#define MAKE_VERSION(a, b, c, d)	(((a) << 24) | ((b) << 16) | (c)<< 8 | (d) )
#define TAVI020_VERSION			MAKE_VERSION(2, 1, 0, 15 )
#define TAVI020_VERSIONSTR		"2.1.0.15"
#define TAVI020_SERIALNO		"T20NM5C00171G"
#define TAVI020_PRODUCTID		"T2G0"
#define TAVI020_COMPILETIME	__DATE__" "__TIME__

#endif
