#define RSM_SETTING					0
#define RSM_PLAY_LIST              		1
#define RSM_BEEP					2
#define RSM_REVERSE_MODE			3
#define RSM_TIME_ZONE				4
#define RSM_LOAD_DEFAULT			5
#define RSM_LANGUAGE				6
#define RSM_RESUME					7
#define RSM_EXCHANGE_BUTTON		8
#define RSM_LOAD_DEFAULT			9
#define RSM_FIRMWARE_UPGRADE		10
#define RSM_FIRMWARE				11
#define RSM_VERSION					12
#define RSM_SPEAKER					13
#define RSM_BEELP_VOLUME			14
#define RSM_BALANCE				15
#define RSM_USER_EQ				16
#define RSM_TREBLE					17
#define RSM_BASS					18
#define RSM_BRIGHTNESS				19
#define RSM_VIDEO_OUTPUT			20
#define RSM_LCD						21
#define RSM_TV						22
#define RSM_DUAL					23
#define RSM_VIDEO_TYPE				24
#define RSM_SCREEN_TYPE			25
#define RSM_LETTER_BOX				26
#define RSM_4ON3_PAN_SCAN			27
#define RSM_16ON9					28
#define RSM_MP4_4ON3_FULL			29
#define RSM_HD_COMPONENT			30
#define RSM_ON						31
#define RSM_OFF						32
#define RSM_HD_DVI					33
#define RSM_POWER_SETTING			34
#define RSM_AUDIO_SETTING			35
#define RSM_GENERAL_SETTING		36
#define RSM_DISPLAY_SETTING		37
#define RSM_CLOCK_SETTING			39
#define RSM_ALARM_SETTING			40
#define RSM_SLEEP_TIMER			41
#define RSM_STOP_POWER_OFF		42
#define RSM_LCD_OFF					43
#define RSM_YEARS					44
#define RSM_HOURS					45
#define RSM_MINUTES				46
#define RSM_SECONDS				47
#define RSM_DAILY					48
#define RSM_AM						49
#define RSM_PM						50
#define RSM_MONTH					51
#define RSM_MONTH1					52
#define RSM_MONTH2					53
#define RSM_MONTH3					54
#define RSM_MONTH4					55
#define RSM_MONTH5					56
#define RSM_MONTH6					57
#define RSM_MONTH7					58
#define RSM_MONTH8					59
#define RSM_MONTH9					60
#define RSM_MONTH10				61
#define RSM_MONTH11				62
#define RSM_MONTH12				63
#define RSM_SEARCH					64
#define RSM_MUSICLIBRARY			65
#define RSM_RESUME					66
#define RSM_MUSICS					67
#define RSM_TODAY					68
#define RSM_FOLDER					69
#define RSM_VOICEREC_FOLDER		70
#define RSM_SEARCH					71
#define RSM_SEARCH_ARTISTS			72
#define RSM_SEARCH_ALBUMS			73
#define RSM_SEARCH_GENRES			74
#define RSM_SEARCH_YEARS			75
#define RSM_SEARCH_TITLES			76
#define RSM_PLAY_ALL				77
#define RSM_BOOKMARK				78
#define RSM_CAPTION_SETTING		79
#define RSM_REPEAT					80
#define RSM_INFO_DISPLAY			81
#define RSM_VIDEO_MODE				82
#define RSM_AUTO					83
#define RSM_AUTO_HIDE				84
#define RSM_SHOW					85
#define RSM_NORMAL					86
#define RSM_WIDE					87
#define RSM_DUAL_CAPTION			88
#define RSM_MAIN_CAPTION			89
#define RSM_SUB_CAPTION			90
#define RSM_CAPTION_POSITION		91
#define RSM_CAPTION_TOP			92
#define RSM_CAPTION_TOP_CENTER	93
#define RSM_CAPTION_BOTTOM		94
#define RSM_CAPTION_BOTTOM_CENTER 95
#define RSM_AUJUST_CAPTION_SYNC	96
#define RSM_BOOK_MARK				97
#define RSM_SAVE_CURRENT_POS_TO_BOOKMARK 98
#define RSM_CAPTION_SELECT			99
#define RSM_SORT_BY_NAME_ASCENT	100
#define RSM_SORT_BY_NAME_DESCENT	101
#define RSM_SORT_BY_DATE_ASCENT	102
#define RSM_SORT_BY_DATE_DESCENT	103
#define RSM_SORT_BY_RANDOM		104
#define RSM_VIEW_LIST				105
#define RSM_VIEW_THUMBNAIL		106
#define RSM_VIEW_PREVIEW			107
#define RSM_PLEASE_CONNECT_EARHONE 108
#define RSM_CHANNEL				109
#define RSM_AUTO_CHANNEL_SCAN	110
#define RSM_PRESET_CHANNEL_LIST	111
#define RSM_NEW_CHANNEL			112
#define RSM_VOICE_RECORDING		113
#define RSM_LINE_IN_RECORDING		114




